/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IndexRouter } from "./IndexRouter";
export * as factories from "./factories";
export { IndexRouter__factory } from "./factories/IndexRouter__factory";
