/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface BaseIndexInterface extends utils.Interface {
  functions: {
    "anatomy()": FunctionFragment;
    "inactiveAnatomy()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "anatomy"
      | "anatomy()"
      | "inactiveAnatomy"
      | "inactiveAnatomy()"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "anatomy", values?: undefined): string;
  encodeFunctionData(functionFragment: "anatomy()", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "inactiveAnatomy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "inactiveAnatomy()",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "anatomy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "anatomy()", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "inactiveAnatomy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inactiveAnatomy()",
    data: BytesLike
  ): Result;

  events: {};
}

export interface BaseIndex extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BaseIndexInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    anatomy(
      overrides?: CallOverrides
    ): Promise<
      [string[], number[]] & { _assets: string[]; _weights: number[] }
    >;

    "anatomy()"(
      overrides?: CallOverrides
    ): Promise<
      [string[], number[]] & { _assets: string[]; _weights: number[] }
    >;

    inactiveAnatomy(overrides?: CallOverrides): Promise<[string[]]>;

    "inactiveAnatomy()"(overrides?: CallOverrides): Promise<[string[]]>;
  };

  anatomy(
    overrides?: CallOverrides
  ): Promise<[string[], number[]] & { _assets: string[]; _weights: number[] }>;

  "anatomy()"(
    overrides?: CallOverrides
  ): Promise<[string[], number[]] & { _assets: string[]; _weights: number[] }>;

  inactiveAnatomy(overrides?: CallOverrides): Promise<string[]>;

  "inactiveAnatomy()"(overrides?: CallOverrides): Promise<string[]>;

  callStatic: {
    anatomy(
      overrides?: CallOverrides
    ): Promise<
      [string[], number[]] & { _assets: string[]; _weights: number[] }
    >;

    "anatomy()"(
      overrides?: CallOverrides
    ): Promise<
      [string[], number[]] & { _assets: string[]; _weights: number[] }
    >;

    inactiveAnatomy(overrides?: CallOverrides): Promise<string[]>;

    "inactiveAnatomy()"(overrides?: CallOverrides): Promise<string[]>;
  };

  filters: {};

  estimateGas: {
    anatomy(overrides?: CallOverrides): Promise<BigNumber>;

    "anatomy()"(overrides?: CallOverrides): Promise<BigNumber>;

    inactiveAnatomy(overrides?: CallOverrides): Promise<BigNumber>;

    "inactiveAnatomy()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    anatomy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "anatomy()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    inactiveAnatomy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "inactiveAnatomy()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
