/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BaseIndex } from "./BaseIndex";
export * as factories from "./factories";
export { BaseIndex__factory } from "./factories/BaseIndex__factory";
