/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { BaseIndex, BaseIndexInterface } from "../BaseIndex";

const _abi = [
  {
    inputs: [],
    name: "anatomy",
    outputs: [
      {
        internalType: "address[]",
        name: "_assets",
        type: "address[]",
      },
      {
        internalType: "uint8[]",
        name: "_weights",
        type: "uint8[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "inactiveAnatomy",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class BaseIndex__factory {
  static readonly abi = _abi;
  static createInterface(): BaseIndexInterface {
    return new utils.Interface(_abi) as BaseIndexInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BaseIndex {
    return new Contract(address, _abi, signerOrProvider) as BaseIndex;
  }
}
