/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IndexDepositRouter,
  IndexDepositRouterInterface,
} from "../IndexDepositRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "index",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        components: [
          {
            internalType: "address",
            name: "input",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "inputAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minOutputAmount",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "swapTarget",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "assetQuote",
            type: "bytes",
          },
        ],
        internalType: "struct IReserveRouter.QuoteParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "deposit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "index",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "deposit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];

export class IndexDepositRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IndexDepositRouterInterface {
    return new utils.Interface(_abi) as IndexDepositRouterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IndexDepositRouter {
    return new Contract(address, _abi, signerOrProvider) as IndexDepositRouter;
  }
}
